- name:	test ansible from git
  hosts: all
  become: yes
  tasks: 
    - name: install apache2
      apt:
        name=apache2 state=present
      notify:
        - restart apache2
   
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
